part of '../../main.dart';

// Category icons
const _categoryIcons = <String, IconData>{
  'Espresso Kahveler': Icons.local_cafe_rounded,
  'Filtre Kahveler': Icons.coffee_maker_rounded,
  'Sıcak İçecekler': Icons.whatshot_rounded,
  'Ice Kahveler': Icons.ac_unit_rounded,
  'LUUQ Kokteyl': Icons.local_bar_rounded,
  'Bitki Çayları': Icons.eco_rounded,
  'Frozen': Icons.severe_cold_rounded,
  'Bubble Tea': Icons.bubble_chart_rounded,
  'Milkshake': Icons.icecream_rounded,
  'Dondurmalar': Icons.icecream_outlined,
  'Meşrubatlar': Icons.sports_bar_rounded,
  'Pasta & Tatlı': Icons.cake_rounded,
  'LUUQ Chocolate': Icons.cookie_rounded,
  'Sandviç': Icons.lunch_dining_rounded,
  'Termos & Seramik': Icons.coffee_rounded,
  'Ekstralar': Icons.add_circle_outline_rounded,
};

// Category descriptions for hero section
const _categoryDescriptions = <String, String>{
  'Espresso Kahveler': 'Yoğun, klasik ve taze espresso bazlı favoriler.',
  'Filtre Kahveler': 'Özenle seçilmiş yöresel çekirdekler ve özel demlemeler.',
  'Sıcak İçecekler': 'İçinizi ısıtacak geleneksel ve modern sıcak lezzetler.',
  'Ice Kahveler': 'Günün her saati ferahlık veren buzlu kahve alternatifleri.',
  'LUUQ Kokteyl':
      'LUUQ imzalı alkolsüz, ferahlatıcı ve özel reçeteli karışımlar.',
  'Bitki Çayları':
      'Doğadan gelen rahatlatıcı ve canlandırıcı özel bitki harmanları.',
  'Frozen': 'Taze meyvelerle hazırlanan buzlu yaz şölenleri.',
  'Bubble Tea':
      'Patlayan boba incileriyle dolu eğlenceli ve serinletici lezzetler.',
  'Milkshake': 'Kıvamlı, yoğun ve tatlı krizlerine birebir sütlü serinlik.',
  'Dondurmalar': 'Yaz aylarının en serinletici ve leziz dondurma çeşitleri.',
  'Meşrubatlar': 'Klasik gazozlar, doğal sodalar ve enerji veren içecekler.',
  'Pasta & Tatlı':
      'Kahvenize mükemmel eşlik edecek taptaze, el yapımı tatlılar.',
  'LUUQ Chocolate': 'LUUQ ustalarından özel yapım premium artizan çikolatalar.',
  'Sandviç': 'Taze ekmeklerle hazırlanan, doyurucu ve leziz atıştırmalıklar.',
  'Termos & Seramik':
      'LUUQ deneyimini gittiğiniz her yere taşıyacak şık tasarımlar.',
  'Ekstralar':
      'İçeceğinizi tamamen kişiselleştirebileceğiniz ekstra dokunuşlar.',
};

// Tag colors
const _tagStyles = <String, Color>{
  'Popüler': Color(0xFFE8B445),
  'Special': Color(0xFFE879A8),
  'Yazın İyisi': Color(0xFF4ECDC4),
  'Soğuk': Color(0xFF74B9FF),
  'Sıcak': Color(0xFFFF7675),
  'Tatlı': Color(0xFFFDA7DF),
  'Sert': Color(0xFFA29BFE),
  'Klasik': Color(0xFFB2BEC3),
  'Yeni': Color(0xFF55EFC4),
};

const _menuCategories = {
  'Espresso Kahveler': [
    _MenuItem(
      'Americano',
      '185₺ / 205₺',
      Icons.local_cafe_rounded,
      desc: 'Sade ve güçlü espresso suyla buluşur',
      tags: ['Klasik'],
      imagePath: 'assets/menu/americano.jpg',
    ),
    _MenuItem(
      'Cappuccino',
      '210₺ / 230₺',
      Icons.local_cafe_rounded,
      desc: 'Kremamsı süt köpüğü ile klasik İtalyan lezzeti',
      tags: ['Sıcak', 'Klasik'],
      imagePath: 'assets/menu/cappucino.jpg',
    ),
    _MenuItem(
      'Caramel Latte',
      '250₺ / 270₺',
      Icons.local_cafe_rounded,
      desc: 'Karamel aromalı sütlü kahve keyfi',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/caramellatte.jpg',
    ),
    _MenuItem(
      'Caramel Macchiato',
      '250₺ / 270₺',
      Icons.local_cafe_rounded,
      desc: 'Karamel sos ve vanilyalı süt',
      tags: ['Tatlı', 'Popüler'],
      imagePath: 'assets/menu/caramelmacchiato.jpg',
    ),
    _MenuItem(
      'Cortado S',
      '200₺',
      Icons.local_cafe_rounded,
      desc: 'Espresso ve az süt, sert ve yoğun',
      imagePath: 'assets/menu/cortado.jpg',
    ),
    _MenuItem(
      'Espresso Double',
      '145₺',
      Icons.local_cafe_rounded,
      desc: 'Çift shot espresso',
      tags: ['Sert'],
      imagePath: 'assets/menu/espressodouble.jpg',
    ),
    _MenuItem(
      'Espresso Single',
      '125₺',
      Icons.local_cafe_rounded,
      desc: 'Tek shot espresso',
      imagePath: 'assets/menu/espressodouble.jpg',
    ),
    _MenuItem(
      'Flat White',
      '250₺',
      Icons.local_cafe_rounded,
      desc: 'İnce dokulu süt ile kadifemsi espresso',
      tags: ['Popüler'],
      imagePath: 'assets/menu/flatwhite.jpg',
    ),
    _MenuItem(
      'Latte',
      '200₺ / 220₺',
      Icons.local_cafe_rounded,
      desc: 'Yumuşak sütlü espresso klasiği',
      tags: ['Sıcak', 'Popüler'],
      imagePath: 'assets/menu/latte.jpg',
    ),
    _MenuItem(
      'Mocha',
      '240₺ / 260₺',
      Icons.local_cafe_rounded,
      desc: 'Çikolata ve espresso buluşması',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/mocha.jpg',
    ),
    _MenuItem(
      'Oreo Latte',
      '240₺ / 260₺',
      Icons.local_cafe_rounded,
      desc: 'Oreo bisküvi parçalı latte',
      imagePath: 'assets/menu/oreolattesicak.jpeg',
    ),
    _MenuItem(
      'White Mocha',
      '240₺ / 260₺',
      Icons.local_cafe_rounded,
      desc: 'Beyaz çikolatalı mocha',
      imagePath: 'assets/menu/whitemocha.jpg',
    ),
  ],
  'Filtre Kahveler': [
    _MenuItem(
      'Cold Brew',
      '220₺',
      Icons.coffee_maker_rounded,
      desc: '12 saat soğuk demleme, yumuşak içim ve ferah kahve aroması.',
      tags: ['Soğuk', 'Popüler'],
    ),
    _MenuItem(
      'Colombia',
      '210₺ / 230₺',
      Icons.coffee_maker_rounded,
      desc: 'Dengeli gövde, zarif asidite ve yumuşak içimli filtre kahve.',
      imagePath: 'assets/menu/klasikfiltre.jpg',
    ),
    _MenuItem(
      'Etiyopya',
      '210₺ / 230₺',
      Icons.coffee_maker_rounded,
      desc: 'Meyvemsi notalar, canlı aroma ve hafif çiçeksi bir bitiş.',
      imagePath: 'assets/menu/klasikfiltre.jpg',
    ),
    _MenuItem(
      'Filtre Sütlü',
      '190₺ / 210₺',
      Icons.coffee_maker_rounded,
      desc: 'Taze filtre kahvenin sütle yumuşatılmış sıcak yorumu.',
    ),
    _MenuItem(
      'Guatamala',
      '210₺ / 230₺',
      Icons.coffee_maker_rounded,
      desc: 'Fındıksı aroma, dolgun gövde ve dengeli kahve karakteri.',
      imagePath: 'assets/menu/klasikfiltre.jpg',
    ),
    _MenuItem(
      'Klasik Filtre',
      '170₺ / 190₺',
      Icons.coffee_maker_rounded,
      desc: 'Günlük taze demlenen, sade ve dengeli klasik filtre kahve.',
      tags: ['Klasik'],
      imagePath: 'assets/menu/klasikfiltre.jpg',
    ),
  ],
  'Sıcak İçecekler': [
    _MenuItem(
      'Chai Tea Latte',
      '265₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Baharatlı çay ve kremamsı süt',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Çay',
      '90₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Geleneksel demlik çay',
      imagePath: 'assets/menu/cay.jpeg',
    ),
    _MenuItem(
      'Damla Sakızlı Sahlep',
      '245₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Damla sakızı aromalı sahlep',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Dondurma Sahlep',
      '255₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Üstü dondurmalı sahlep',
    ),
    _MenuItem(
      'Double Türk Kahvesi',
      '160₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Çift pişirme Türk kahvesi',
      tags: ['Sert'],
      imagePath: 'assets/menu/turkkahvesi.jpg',
    ),
    _MenuItem(
      'Frambuazlı Sıcak Beyaz Çikolata',
      '245₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Frambuaz ve beyaz çikolata',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/frambuazsicakbeyazcikolata.jpg',
    ),
    _MenuItem(
      'Sıcak Çikolata',
      '235₺ / 255₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Yoğun kakao lezzeti',
      tags: ['Tatlı', 'Popüler'],
      imagePath: 'assets/menu/sicakcikolata.jpeg',
    ),
    _MenuItem(
      'Tarçınlı Sahlep',
      '235₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Tarçın aromalı geleneksel sahlep',
    ),
    _MenuItem(
      'Türk Kahvesi',
      '140₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Geleneksel köpüklü Türk kahvesi',
      tags: ['Klasik'],
      imagePath: 'assets/menu/turkkahvesi.jpg',
    ),
    _MenuItem(
      'Mocha Mint',
      '250₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Naneli mocha',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Nuttymix',
      '250₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Fındıklı karışım',
      tags: ['Sıcak'],
      imagePath: 'assets/menu/png/latte.png',
    ),
    _MenuItem(
      'Raspberry Mocha',
      '250₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Frambuazlı mocha',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Vani Gold',
      '240₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Vanilyalı altın kokteyl',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Vanicha',
      '240₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Vanilya ve matcha füzyonu',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Vitte Latte',
      '240₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Beyaz çikolatalı latte',
      tags: ['Sıcak'],
    ),
    _MenuItem(
      'Vitte Milk',
      '240₺',
      Icons.emoji_food_beverage_rounded,
      desc: 'Beyaz çikolatalı süt',
      tags: ['Sıcak'],
    ),
  ],
  'Ice Kahveler': [
    _MenuItem(
      'Affogato',
      '240₺',
      Icons.ac_unit_rounded,
      desc: 'Espresso üzerine dondurma',
      tags: ['Soğuk', 'Tatlı'],
    ),
    _MenuItem(
      'Ice Americano',
      '185₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu sade americano',
      tags: ['Soğuk'],
      imagePath: 'assets/menu/iceamericano.jpg',
    ),
    _MenuItem(
      'Ice Caramel Latte',
      '250₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu karamel latte',
      tags: ['Soğuk', 'Tatlı'],
      imagePath: 'assets/menu/icecaramellatte.jpg',
    ),
    _MenuItem(
      'Ice Caramel Macchiato',
      '250₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu karamel macchiato',
      tags: ['Soğuk', 'Popüler'],
      imagePath: 'assets/menu/icecaramelmacchiato.jpg',
    ),
    _MenuItem(
      'Ice Filtre Kahve',
      '170₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu filtre kahve',
    ),
    _MenuItem(
      'Ice Flat White',
      '250₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu flat white',
      imagePath: 'assets/menu/iceflatwhite.jpg',
    ),
    _MenuItem(
      'Ice Latte',
      '200₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu sütlü espresso',
      tags: ['Soğuk', 'Popüler'],
      imagePath: 'assets/menu/icelatte.jpg',
    ),
    _MenuItem(
      'Ice Mocha',
      '240₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu çikolatalı mocha',
      tags: ['Soğuk', 'Tatlı'],
      imagePath: 'assets/menu/icemocha.jpg',
    ),
    _MenuItem(
      'Ice Oreo Latte',
      '235₺',
      Icons.ac_unit_rounded,
      desc: 'Oreo parçalı buzlu latte',
      tags: ['Soğuk', 'Tatlı'],
      imagePath: 'assets/menu/oreolatteice.jpeg',
    ),
    _MenuItem(
      'Ice Sütlü Filtre Kahve',
      '190₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu sütlü filtre',
      imagePath: 'assets/menu/icesutlufiltrekahve.jpg',
    ),
    _MenuItem(
      'Ice White Mocha',
      '240₺',
      Icons.ac_unit_rounded,
      desc: 'Buzlu beyaz mocha',
      imagePath: 'assets/menu/icewhitemocha.jpg',
    ),
  ],
  'LUUQ Kokteyl': [
    _MenuItem(
      'Beach of Luuq',
      '260₺',
      Icons.local_bar_rounded,
      desc: 'Tropikal meyveli serinletici kokteyl',
      tags: ['Yazın İyisi', 'Special'],
    ),
    _MenuItem(
      'Butterfly Effect',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Renk değiştiren büyüleyici kokteyl',
      tags: ['Special'],
      imagePath: 'assets/menu/buttferflyeffect.jpg',
    ),
    _MenuItem(
      'Caramel Affogato',
      '280₺',
      Icons.local_bar_rounded,
      desc: 'Karamelli affogato yorumu',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/caramelaffogato.jpg',
    ),
    _MenuItem(
      'Casablanca',
      '260₺',
      Icons.local_bar_rounded,
      desc: 'Egzotik meyve karışımı',
      tags: ['Special'],
    ),
    _MenuItem(
      'Cool Lime',
      '260₺',
      Icons.local_bar_rounded,
      desc: 'Ferahlatıcı misket limonu',
      tags: ['Yazın İyisi'],
      imagePath: 'assets/menu/coollime.jpg',
    ),
    _MenuItem(
      'Ginger Dragon',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Zencefilli ejderha meyveli',
      tags: ['Special'],
    ),
    _MenuItem(
      'Guava Bomb',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Guava patlaması',
    ),
    _MenuItem(
      'Ice Matcha Latte',
      '240₺',
      Icons.local_bar_rounded,
      desc: 'Buzlu matcha sütlü',
      tags: ['Soğuk', 'Popüler'],
    ),
    _MenuItem(
      'Ice Pistachio Dream',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Antep fıstıklı rüya',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/pistachiodream.jpg',
    ),
    _MenuItem(
      'Luuq Kuzu Kulağı Kokteyl',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Kuzu kulağı otlu özel tarif',
      tags: ['Special'],
      imagePath: 'assets/menu/kuzukulagi.jpg',
    ),
    _MenuItem(
      'Matcha Mix',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Matcha karışım kokteyl',
      imagePath: 'assets/menu/matchamix.jpg',
    ),
    _MenuItem(
      'Mazagran',
      '250₺',
      Icons.local_bar_rounded,
      desc: 'Limonlu soğuk kahve',
    ),
    _MenuItem(
      'Rubiqa Mocha',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Rubika özel mocha',
      tags: ['Special'],
      imagePath: 'assets/menu/rubycamocha.jpeg',
    ),
    _MenuItem(
      'Savaya',
      '270₺',
      Icons.local_bar_rounded,
      desc: 'Tropikal lezzet',
      tags: ['Special'],
    ),
    _MenuItem(
      'Strawberry Cool Lime',
      '260₺',
      Icons.local_bar_rounded,
      desc: 'Çilekli misket limonu',
      tags: ['Yazın İyisi'],
      imagePath: 'assets/menu/strawberrycoollime.jpg',
    ),
    _MenuItem(
      'Sweet & Sour Mix',
      '260₺',
      Icons.local_bar_rounded,
      desc: 'Tatlı ekşi karışım',
    ),
    _MenuItem(
      'Turkish Dream',
      '240₺',
      Icons.local_bar_rounded,
      desc: 'Türk kahveli özel kokteyl',
      tags: ['Special'],
    ),
    _MenuItem(
      'Waffle Juice',
      '260₺',
      Icons.local_bar_rounded,
      desc: 'Waffle aromalı taze sıkım',
      tags: ['Yeni'],
    ),
  ],
  'Bitki Çayları': [
    _MenuItem(
      'Ahududu Limon',
      '220₺',
      Icons.eco_rounded,
      desc: 'Ahududu ve taze limonun canlandırıcı uyumu',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
    _MenuItem(
      'Green Carnaval',
      '220₺',
      Icons.eco_rounded,
      desc: 'Egzotik yeşil çay ve meyve harmonisi',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
    _MenuItem(
      'Gripsavar',
      '220₺',
      Icons.eco_rounded,
      desc: 'Bağışıklık destekleyici zencefil, limon ve bal kürü',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
    _MenuItem(
      'Limon Zencefil',
      '220₺',
      Icons.eco_rounded,
      desc: 'Ferahlatıcı limon ve canlandırıcı zencefil',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
    _MenuItem(
      'Madagascar',
      '220₺',
      Icons.eco_rounded,
      desc: 'Özel baharatlar ve Madagaskar vanilyası harmanı',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
    _MenuItem(
      'Magic Of Bali',
      '220₺',
      Icons.eco_rounded,
      desc: 'Uzak doğunun mistik bitkisel lezzeti',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
    _MenuItem(
      'Relax',
      '220₺',
      Icons.eco_rounded,
      desc: 'Günün stresini alan rahatlatıcı papatya ve melisa',
      imagePath: 'assets/menu/bitkicayi.jpeg',
    ),
  ],
  'Frozen': [
    _MenuItem(
      'Frozen Ananas & Portakal & Limon',
      '265₺',
      Icons.severe_cold_rounded,
      desc: 'Ananas, portakal ve limonun ferah tropikal buluşması.',
      tags: ['Soğuk'],
      imagePath: 'assets/menu/frozenananasportakallimon.jpg',
    ),
    _MenuItem(
      'Frozen Karpuz & Çilek',
      '265₺',
      Icons.severe_cold_rounded,
      desc: 'Karpuzun serinliği, çileğin tatlı aromasıyla birleşir.',
      tags: ['Yazın İyisi', 'Soğuk'],
      imagePath: 'assets/menu/frozenkarpuzcilek.jpg',
    ),
    _MenuItem(
      'Frozen Mango',
      '265₺',
      Icons.severe_cold_rounded,
      desc: 'Yoğun mango aromasıyla egzotik ve ferah bir frozen.',
      tags: ['Soğuk'],
      imagePath: 'assets/menu/frozenmango.jpg',
    ),
    _MenuItem(
      'Frozen Orman Meyveleri',
      '265₺',
      Icons.severe_cold_rounded,
      desc: 'Orman meyvelerinin tatlı-ekşi ferahlığıyla hazırlanır.',
      tags: ['Soğuk', 'Popüler'],
      imagePath: 'assets/menu/frozenormanmeyveleri.jpg',
    ),
    _MenuItem(
      'Frozen Yuzu & Şeftali',
      '265₺',
      Icons.severe_cold_rounded,
      desc: 'Yuzu ferahlığı ve şeftali tatlılığı bir arada.',
      tags: ['Soğuk', 'Yeni'],
      imagePath: 'assets/menu/frozenyuzuseftali.jpg',
    ),
  ],
  'Bubble Tea': [
    _MenuItem(
      'Çilekli Limonata',
      '230₺',
      Icons.bubble_chart_rounded,
      desc: 'Çilek aromasıyla canlanan ferah ve serin limonata.',
      tags: ['Soğuk'],
    ),
    _MenuItem(
      'Fresh Bubble Tea',
      '250₺',
      Icons.bubble_chart_rounded,
      desc: 'Taptaze meyveler ve boba incileriyle ferah bir bubble tea.',
      tags: ['Soğuk'],
      imagePath: 'assets/menu/freshbubble.jpg',
    ),
    _MenuItem(
      'Jungle Bubble Tea',
      '250₺',
      Icons.bubble_chart_rounded,
      desc: 'Tropik meyveler ve yeşil elma boba ile canlı bir içim.',
      tags: ['Yeni', 'Soğuk'],
      imagePath: 'assets/menu/junglebubletea.jpg',
    ),
    _MenuItem(
      'Mango Bubble Tea',
      '250₺',
      Icons.bubble_chart_rounded,
      desc: 'Yoğun mango aroması ve boba incileriyle tropik lezzet.',
      tags: ['Soğuk'],
      imagePath: 'assets/menu/mangobubbletea.jpg',
    ),
    _MenuItem(
      'Naneli Limonata',
      '210₺',
      Icons.bubble_chart_rounded,
      desc: 'Nane ferahlığıyla zenginleşen serin limonata keyfi.',
      tags: ['Soğuk'],
    ),
    _MenuItem(
      'Strawberry Bubble Tea',
      '250₺',
      Icons.bubble_chart_rounded,
      desc: 'Çilek aroması ve boba incileriyle tatlı, eğlenceli bir içim.',
      tags: ['Popüler', 'Tatlı'],
      imagePath: 'assets/menu/strawberrybubbletea.jpg',
    ),
  ],
  'Milkshake': [
    _MenuItem(
      'Milkshake Beyaz Çikolata & Fındık',
      '265₺',
      Icons.icecream_rounded,
      desc: 'Kremamsı beyaz çikolata ve kavrulmuş fındık',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/beyazcikolatafindik.jpg',
    ),
    _MenuItem(
      'Milkshake Bitter & Portakal',
      '265₺',
      Icons.icecream_rounded,
      desc: 'Yoğun bitter çikolata ve taze portakal aroması',
      tags: ['Tatlı'],
      imagePath: 'assets/menu/bitterportakal.jpg',
    ),
    _MenuItem(
      'Milkshake Cinderella',
      '265₺',
      Icons.icecream_rounded,
      desc: 'Çilek, vanilya ve sihirli süslemeler',
      tags: ['Special', 'Tatlı'],
      imagePath: 'assets/menu/cindirella.jpg',
    ),
    _MenuItem(
      'Milkshake Morocco',
      '265₺',
      Icons.icecream_rounded,
      desc: 'Egzotik baharatlı karamel rüyası',
      tags: ['Yeni'],
      imagePath: 'assets/menu/morocco.jpg',
    ),
    _MenuItem(
      'Milkshake Nutella',
      '265₺',
      Icons.icecream_rounded,
      desc: 'Orijinal Nutella ile hazırlanan yoğun lezzet',
      tags: ['Popüler', 'Tatlı'],
      imagePath: 'assets/menu/nutellamilshake.jpg',
    ),
    _MenuItem(
      'Milkshake Tahin & Karamel & Çilek',
      '265₺',
      Icons.icecream_rounded,
      desc: 'Geleneksel tahin, karamel ve çilek füzyonu',
      tags: ['Special'],
      imagePath: 'assets/menu/toffenutkaramelcilek.jpg',
    ),
  ],
  'Meşrubatlar': [
    _MenuItem(
      'Beyoğlu Klasik',
      '125₺',
      Icons.sports_bar_rounded,
      desc: 'Klasik Beyoğlu gazozu ferahlığı',
    ),
    _MenuItem(
      'Beyoğlu Reyhan',
      '125₺',
      Icons.sports_bar_rounded,
      desc: 'Reyhan aromalı efsanevi gazoz',
    ),
    _MenuItem(
      'Beyoğlu Zencefil',
      '125₺',
      Icons.sports_bar_rounded,
      desc: 'Zencefil aromalı serinletici gazoz',
    ),
    _MenuItem(
      'Redbull',
      '170₺',
      Icons.sports_bar_rounded,
      desc: 'Enerji veren klasik lezzet',
    ),
    _MenuItem(
      'Damla Soda (200 ml)',
      '90₺',
      Icons.sports_bar_rounded,
      desc: 'Doğal mineralli su',
    ),
    _MenuItem(
      'Damla Soda (330 ml)',
      '100₺',
      Icons.sports_bar_rounded,
      desc: 'Doğal mineralli su büyük boy',
    ),
    _MenuItem(
      'Damla Cam Su (330 ml)',
      '60₺',
      Icons.sports_bar_rounded,
      desc: 'Cam şişede doğal kaynak suyu',
    ),
    _MenuItem(
      'Uludağ Premium Soda',
      '100₺',
      Icons.sports_bar_rounded,
      desc: 'Özel cam şişede premium maden suyu',
    ),
  ],
  'Dondurmalar': [
    _MenuItem(
      'Vanilya',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Klasik ve yoğun gerçek vanilya çekirdeği lezzeti.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Kakao',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Yoğun çikolata dolgulu geleneksel kakao keyfi.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Karamel',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Karamel soslu tatlı ve kremamsı dondurma.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Antep Fıstığı',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Taze Antep fıstığı parçacıklarıyla zenginleşen lezzet.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Limon',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Ekşi ve ferahlatıcı gerçek limon aroması.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Kavun',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Yaz kavununun tatlı ve sulu serinliği.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Çilek',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Taze yaz çilekleriyle hazırlanan meyveli dondurma.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Karadut',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Doğal karadut taneleriyle tatlı-ekşi ferahlık.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Bal Badem',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Süzme bal ve çıtır badem parçacıklarının uyumu.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Bubble Gum',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Eğlenceli sakız aromalı çocuksu tat.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Blue Sky',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Farklı ve özel aromasıyla gökyüzü mavisi lezzet.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Meyve Şöleni',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Karışık yaz meyvelerinin eşsiz uyumu.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
    _MenuItem(
      'Oreo',
      '100₺',
      Icons.icecream_outlined,
      desc: 'Çıtır Oreo bisküvi parçacıklarıyla kremamsı dondurma.',
      tags: ['Yazın İyisi', 'Soğuk'],
    ),
  ],
  'Pasta & Tatlı': [
    _MenuItem(
      'Allgo Dom Pasta',
      '295₺',
      Icons.cake_rounded,
      desc: 'Özel kubbe tasarım çikolatalı pasta',
      tags: ['Special', 'Tatlı'],
    ),
    _MenuItem(
      'Ananas Badem Mono Pasta',
      '295₺',
      Icons.cake_rounded,
      desc: 'Ananas ve bademin hafif tatlı uyumu',
    ),
    _MenuItem(
      'Antep Dolgulu Cheesecake',
      '295₺',
      Icons.cake_rounded,
      desc: 'İçi bol fıstıklı çıtır cheesecake',
      tags: ['Popüler'],
      imagePath: 'assets/menu/antepcheesecake.jpeg',
    ),
    _MenuItem(
      'Antep Fıstıklı Tart',
      '305₺',
      Icons.cake_rounded,
      desc: 'Bol fıstıklı çıtır hamurlu Fransız tartı',
    ),
    _MenuItem(
      'Bademli Kruvasan',
      '295₺',
      Icons.cake_rounded,
      desc: 'Taze fırınlanmış badem kremalı kruvasan',
    ),
    _MenuItem(
      'Blondie Limon',
      '305₺',
      Icons.cake_rounded,
      desc: 'Limon ferahlığıyla beyaz çikolatalı blondie',
      tags: ['Yeni'],
    ),
    _MenuItem(
      'Cheesecake Patlayan Şeker',
      '285₺',
      Icons.cake_rounded,
      desc: 'Ağızda patlayan şekerli eğlenceli tatlı',
      tags: ['Special'],
    ),
    _MenuItem(
      'Cheesecake San Sebastian',
      '295₺',
      Icons.cake_rounded,
      desc: 'Yanık kabuklu, akışkan içiyle İspanyol klasiği',
      tags: ['Popüler', 'Klasik'],
      imagePath: 'assets/menu/sansebastian.jpeg',
    ),
    _MenuItem(
      'Çikolatalı Cookie Pie',
      '400₺',
      Icons.cake_rounded,
      desc: 'Dev çikolatalı kurabiye turtası',
      tags: ['Tatlı'],
    ),
    _MenuItem(
      'Çikolatalı Tırtıl Pasta',
      '285₺',
      Icons.cake_rounded,
      desc: 'Çocukların favorisi çikolatalı özel pasta',
    ),
    _MenuItem(
      'Elmalı Tart',
      '295₺',
      Icons.cake_rounded,
      desc: 'Tarçın ve karamelize elmalı çıtır tart',
      tags: ['Klasik'],
    ),
    _MenuItem(
      'Fındıklı Kruvasan',
      '295₺',
      Icons.cake_rounded,
      desc: 'Fındık kreması dolgulu sıcak kruvasan',
    ),
    _MenuItem(
      'Frambuaz & Antep Fıstıklı Kek',
      '295₺',
      Icons.cake_rounded,
      desc: 'Hafif ekşi frambuaz ve yeşil fıstık şöleni',
    ),
    _MenuItem(
      'Frambuazlı Mono Pasta',
      '295₺',
      Icons.cake_rounded,
      desc: 'Tek kişilik taze meyveli hafif pasta',
    ),
    _MenuItem(
      'Kesme Fındıklı Pasta',
      '435₺',
      Icons.cake_rounded,
      desc: 'Geleneksel kesme dondurma formunda pasta',
    ),
    _MenuItem(
      'Lime Ekler',
      '295₺',
      Icons.cake_rounded,
      desc: 'Misket limonu kremalı hafif ekler',
      tags: ['Yeni'],
    ),
    _MenuItem(
      'Limon & Frangipane Tart',
      '305₺',
      Icons.cake_rounded,
      desc: 'Badem kremalı limonlu zarif tart',
    ),
    _MenuItem(
      'Limon & Haşhaşlı Baton Kek',
      '155₺',
      Icons.cake_rounded,
      desc: 'Çıtır haşhaş ve taze limonlu kek dilimi',
    ),
    _MenuItem(
      'Lotus Mono Ekler',
      '295₺',
      Icons.cake_rounded,
      desc: 'Orijinal Lotus bisküvi kremalı porsiyonluk ekler',
      tags: ['Popüler'],
    ),
    _MenuItem(
      'Luuq Çikolatalı Mousse Pasta',
      '285₺',
      Icons.cake_rounded,
      desc: 'Köpüksü hafifliğiyle yoğun çikolata',
      tags: ['Special'],
    ),
    _MenuItem(
      'Mermer Baton Kek',
      '155₺',
      Icons.cake_rounded,
      desc: 'Vanilya ve kakaolu klasik mermer kek',
    ),
    _MenuItem(
      'Oreo Cheesecake',
      '305₺',
      Icons.cake_rounded,
      desc: 'Bol Oreo bisküvili klasik peynir tatlısı',
    ),
    _MenuItem(
      'Orman Meyveli Cup',
      '285₺',
      Icons.cake_rounded,
      desc: 'Bardakta taze meyveli kat kat lezzet',
    ),
    _MenuItem(
      'Orman Meyveli Elips Tart',
      '285₺',
      Icons.cake_rounded,
      desc: 'Özel şekliyle orman meyveli çıtır tart',
    ),
    _MenuItem(
      'Paris Breast',
      '295₺',
      Icons.cake_rounded,
      desc: 'Halka şeklinde badem kremalı Fransız tatlısı',
      tags: ['Special'],
    ),
    _MenuItem(
      'Passion & Çikolatalı Tart',
      '295₺',
      Icons.cake_rounded,
      desc: 'Çarkıfelek meyvesi ve çikolata buluşması',
    ),
    _MenuItem(
      'Smores Cup',
      '285₺',
      Icons.cake_rounded,
      desc: 'Kızarmış marshmallow ve çikolatalı kupa',
      tags: ['Yeni'],
    ),
    _MenuItem(
      'Tiramisu',
      '285₺',
      Icons.cake_rounded,
      desc: 'Espresso ile ıslatılmış mascarpone peynirli klasik',
      tags: ['Klasik'],
    ),
    _MenuItem(
      'Trio Chocolate Browni',
      '265₺',
      Icons.cake_rounded,
      desc: 'Üç çikolatalı yoğun brownie',
      tags: ['Popüler'],
      imagePath: 'assets/menu/brownie.jpeg',
    ),
    _MenuItem(
      'Üçgen Dilim Fıstıklı Cheesecake',
      '435₺',
      Icons.cake_rounded,
      desc: 'Yoğun fıstıklı dilimlenmiş dev cheesecake',
    ),
    _MenuItem(
      'Vişneli Tart',
      '305₺',
      Icons.cake_rounded,
      desc: 'Ekşi vişnelerle dengelenmiş tatlı tart',
    ),
    _MenuItem(
      'Vişneli Brownie',
      '275₺',
      Icons.cake_rounded,
      desc: 'İçi ıslak, vişne taneli brownie rüyası',
      imagePath: 'assets/menu/visnelibrownie.jpeg',
    ),
    _MenuItem(
      'White Cascada Dom Pasta',
      '285₺',
      Icons.cake_rounded,
      desc: 'Beyaz çikolatalı şelale tasarımlı pasta',
      imagePath: 'assets/menu/whitecascada.jpeg',
    ),
    _MenuItem(
      'Brownie Dream',
      '285₺',
      Icons.cake_rounded,
      desc: 'Özel krema dolgulu enfes brownie rüyası',
      imagePath: 'assets/menu/browniedream.jpeg',
    ),
    _MenuItem(
      'Çilek Limon Mono Pasta',
      '295₺',
      Icons.cake_rounded,
      desc: 'Çilek ve limon ferahlığıyla mono pasta',
      imagePath: 'assets/menu/cileklimonopasta.jpeg',
    ),
    _MenuItem(
      'Limonlu Pasta',
      '295₺',
      Icons.cake_rounded,
      desc: 'Limon soslu ve kremalı nefis pasta dilimi',
      imagePath: 'assets/menu/limonlupasta.jpeg',
    ),
    _MenuItem(
      'Yanık Cheesecake',
      '305₺',
      Icons.cake_rounded,
      desc: 'San Sebastian tarzı yanık üst kabuklu',
    ),
  ],
  'LUUQ Chocolate': [
    _MenuItem(
      'Luuq Chocolate Delight',
      '410₺',
      Icons.cookie_rounded,
      desc: 'Luuq ustalarından özel çikolata lokumu',
      tags: ['Special'],
      imagePath: 'assets/menu/luuqchocolatedelight.jpg',
    ),
    _MenuItem(
      'Luuq Chocolate Joy',
      '410₺',
      Icons.cookie_rounded,
      desc: 'Fındık ve fıstık dolgulu neşe küpleri',
      imagePath: 'assets/menu/luuqchocolatejoy.jpg',
    ),
    _MenuItem(
      'Luuq Cream Puff',
      '445₺',
      Icons.cookie_rounded,
      desc: 'İçi taze krema dolgulu çikolata topları',
      imagePath: 'assets/menu/luuqcreampuff.jpg',
    ),
    _MenuItem(
      'Luuq Crispy Dream',
      '445₺',
      Icons.cookie_rounded,
      desc: 'Çıtır gofret parçalı rüya gibi çikolata',
      imagePath: 'assets/menu/luuqcrispydream.jpg',
    ),
    _MenuItem(
      'Luuq Dubai Chocolate Cup',
      '445₺',
      Icons.cookie_rounded,
      desc: 'Künefe ve fıstık dolgulu meşhur Dubai çikolatası',
      tags: ['Popüler', 'Yeni'],
      imagePath: 'assets/menu/luuqdubaichocolatecup.jpg',
    ),
    _MenuItem(
      'Luuq White Chocolate Delight',
      '410₺',
      Icons.cookie_rounded,
      desc: 'Beyaz çikolata sevenlere özel spesiyal',
      imagePath: 'assets/menu/luuqwhitechocolatedelight.jpg',
    ),
  ],
  'Sandviç': [
    _MenuItem(
      'Dana Jambon',
      '275₺',
      Icons.lunch_dining_rounded,
      desc: 'Taze yeşilliklerle dana jambonlu sandviç',
    ),
    _MenuItem(
      'Haşhaşlı Cabata Sandviç',
      '275₺',
      Icons.lunch_dining_rounded,
      desc: 'Haşhaşlı taze ekmek içinde özel peynir',
    ),
    _MenuItem(
      'Ezine Peynirli Tahıllı Cabata Sandviç',
      '275₺',
      Icons.lunch_dining_rounded,
      desc: 'Tam tahıllı ekmek, ezine peyniri ve domates',
      tags: ['Klasik'],
    ),
    _MenuItem(
      'Haşhaşlı 4 Peynirli Bagel Sandviç',
      '265₺',
      Icons.lunch_dining_rounded,
      desc: 'Erimiş 4 peynirli doyurucu bagel',
    ),
    _MenuItem(
      'Haşhaşlı Cabata Hindi Füme Tahıllı',
      '275₺',
      Icons.lunch_dining_rounded,
      desc: 'Hindi füme ve yeşillikli hafif öğün',
    ),
    _MenuItem(
      'Cabata Sandviç',
      '275₺',
      Icons.lunch_dining_rounded,
      desc: 'Günlük taze cabata ekmeğine lezzetler',
    ),
    _MenuItem(
      'Pesto Soslu Tavuklu Sandviç',
      '295₺',
      Icons.lunch_dining_rounded,
      desc: 'İtalyan pesto soslu ızgara tavuk',
      tags: ['Popüler'],
    ),
    _MenuItem(
      'Tahıllı Üçgen Panini',
      '285₺',
      Icons.lunch_dining_rounded,
      desc: 'Tost makinesinde ısıtılmış kaşarlı panini',
    ),
    _MenuItem(
      'Yedi Foccacia Ezine Peynirli Sandviç',
      '295₺',
      Icons.lunch_dining_rounded,
      desc: 'Zeytinyağlı foccacia arası ezine',
    ),
    _MenuItem(
      'Yedi Foccacia Hindi Sandviç',
      '295₺',
      Icons.lunch_dining_rounded,
      desc: 'İtalyan ekmeğinde ince dilim hindi füme',
    ),
    _MenuItem(
      'Yedi Roast Beef Sandviç',
      '285₺',
      Icons.lunch_dining_rounded,
      desc: 'Közlenmiş biber ve roast beef eti',
      tags: ['Special'],
    ),
    _MenuItem(
      'Yulaflı Cabata',
      '250₺',
      Icons.lunch_dining_rounded,
      desc: 'Yulaf ezmeli sağlıklı sandviç seçeneği',
    ),
  ],
  'Termos & Seramik': [
    _MenuItem(
      'Seramik Demlik',
      '1750₺',
      Icons.coffee_rounded,
      desc: 'El yapımı özel seramik çay demliği',
    ),
    _MenuItem(
      'Seramik Double Türk Kahvesi Seti',
      '1200₺',
      Icons.coffee_rounded,
      desc: 'İki kişilik şık Türk kahvesi fincan takımı',
    ),
    _MenuItem(
      'Seramik Kupa - Altlık',
      '1200₺',
      Icons.coffee_rounded,
      desc: 'Tabağıyla birlikte el yapımı kahve kupası',
    ),
    _MenuItem(
      'Seramik Pasta Tabağı',
      '1200₺',
      Icons.coffee_rounded,
      desc: 'Tatlı sunumları için özel tasarım tabak',
    ),
    _MenuItem(
      'Seramik Türk Kahvesi Seti',
      '1200₺',
      Icons.coffee_rounded,
      desc: 'Tek kişilik özel tasarım kahve seti',
    ),
    _MenuItem(
      'Trm04s Rose 400 ml Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Rose gold renkli şık çelik termos',
    ),
    _MenuItem(
      'Trm094 Beyaz Ofset 350 ml Çelik Termos',
      '720₺',
      Icons.coffee_rounded,
      desc: 'Minimal beyaz tasarımlı kompakt termos',
    ),
    _MenuItem(
      'Trm094 K.rengi Ofset 350 ml Çelik Termos',
      '720₺',
      Icons.coffee_rounded,
      desc: 'Kahverengi tonlarında sızdırmaz termos',
    ),
    _MenuItem(
      'Trm119 Siyah 500 ml Çelik Mug Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Mat siyah geniş hacimli mug termos',
    ),
    _MenuItem(
      'Trm159 Haki 350 ml Çelik Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Haki yeşili dayanıklı çelik termos',
    ),
    _MenuItem(
      'Trm159 Krem 350 ml Çelik Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Krem renkli zarif çelik termos',
    ),
    _MenuItem(
      'Trm175 Siyah 500 ml Çelik Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Isı yalıtımlı mat siyah çelik termos',
    ),
    _MenuItem(
      'Trm173 Yeşil 350 ml Çelik Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Doğa yeşili tonlarında şık termos',
    ),
    _MenuItem(
      'Trm185-B 380 ml Beyaz Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Ergonomik beyaz renkli pratik termos',
    ),
    _MenuItem(
      'Trm185-G 380 ml Gri Termos',
      '995₺',
      Icons.coffee_rounded,
      desc: 'Modern gri tasarımlı günlük termos',
    ),
  ],
  'Ekstralar': [
    _MenuItem(
      'Bademli Süt',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçeceğinize vegan badem sütü alternatifi',
    ),
    _MenuItem(
      'Bubble',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçeceğinize ekstra patlayan meyve incileri',
    ),
    _MenuItem(
      'Balparmak (7 gr)',
      '100₺',
      Icons.add_circle_outline_rounded,
      desc: 'Tek kullanımlık doğal süzme bal',
    ),
    _MenuItem(
      'Calebaut',
      '80₺',
      Icons.add_circle_outline_rounded,
      desc: 'Gerçek Belçika çikolatası ilavesi',
    ),
    _MenuItem(
      'Dondurma',
      '75₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçeceğinizin veya tatlınızın yanına bir top dondurma',
    ),
    _MenuItem(
      'Ekstra Çilek (Meyve)',
      '80₺',
      Icons.add_circle_outline_rounded,
      desc: 'Taze çilek dilimleri ilavesi',
    ),
    _MenuItem(
      'Ekstra Muz (Meyve)',
      '60₺',
      Icons.add_circle_outline_rounded,
      desc: 'Taze muz dilimleri ilavesi',
    ),
    _MenuItem(
      'Laktozsuz Süt',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'Hassas mideler için laktozsuz süt alternatifi',
    ),
    _MenuItem(
      'Fındık Süt',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçeceğinize fındık aromalı bitkisel süt',
    ),
    _MenuItem(
      'Krema',
      '30₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçeceğinizin üzerine taze krem şanti',
    ),
    _MenuItem(
      'Püre',
      '30₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçecekler için ekstra meyve püresi',
    ),
    _MenuItem(
      'Shot',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'Kahvenize ekstra bir shot espresso',
    ),
    _MenuItem(
      'Sos',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'Tatlınıza veya içeceğinize ekstra çikolata/karamel sos',
    ),
    _MenuItem(
      'Şurup',
      '30₺',
      Icons.add_circle_outline_rounded,
      desc: 'Farklı aromalarda ekstra şurup ilavesi',
    ),
    _MenuItem(
      'Yulaf Süt',
      '50₺',
      Icons.add_circle_outline_rounded,
      desc: 'İçeceğinize vegan yulaf sütü alternatifi',
    ),
  ],
};
